
```{r, echo=FALSE, message=FALSE}
library(tidyverse)
library(plotly)
library(MetBrewer)

country <- read_csv("files/membership_by_country.csv")
member_population <- read_csv("files/membership_and_population.csv")

member_population_clean <- member_population |>
  select(Country, Area, Members, Population, `2022`, `%LDS`)

east_europe <- member_population_clean |> 
  filter(Area == "Europe East")

central_europe <- member_population_clean |> 
  filter(Area == "Europe Central")

unassigned <- member_population_clean |> 
  filter(Area == "Unassigned**")

europe <- rbind(east_europe, central_europe, unassigned)

north_europe <- member_population_clean |> 
  filter(Area == "Europe North")

clean_north_europe <- north_europe |>
  filter(!row_number() %in% c(1)) 
```

## Europe

```{r, echo=FALSE}
#| fig-width: 6
#| fig-height: 6
member_percent <- europe |> 
  mutate(Country = fct_reorder(Country, Population)) |> 
  ggplot(aes(x = Country, 
             y = `%LDS`, 
             text = Population, 
             words = Members,
             color = `%LDS`,
             things = `%LDS`))+
  geom_point()+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, hjust = 0.5, vjust = 0.5))+
  labs(title = "Population and Membership: Central and East Europe",
       x = NULL)

ggplotly(member_percent, tooltip = c("text", "words", "things"))
```

```{r, echo=FALSE}
#| fig-width: 6
#| fig-height: 6
north_europe_percent <- clean_north_europe |> 
    mutate(Country = fct_reorder(Country, Population)) |> 
  ggplot(aes(x = Country, 
             y = `%LDS`, 
             text = Population, 
             words = Members, 
             things = `%LDS`, 
             color = `%LDS`))+
  geom_point()+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, hjust = 0.5, vjust = 0.5))+
  labs(title = "Population and Membership: Northern Europe",
       x = NULL)
  

ggplotly(north_europe_percent, tooltip = c("text", "words", "things"))
```

```{r, echo=FALSE}
#| fig-width: 8
#| fig-height: 7
europe_plot <- europe |> 
  mutate(Country = fct_reorder(Country, Members)) |> 
  ggplot(aes(x = Members, y = Country))+ 
  geom_point()+
  theme_bw()+
  labs(title = "Membership by Country: Europe",
       subtitle = "Plot 1",
       y = NULL)
europe_plot
```

```{r, echo=FALSE}
#| fig-width: 6
#| fig-height: 6
north_europe_plot <- clean_north_europe |> 
  mutate(Country = fct_reorder(Country, Members)) |> 
  ggplot(aes(x = Members, y = Country))+ 
  geom_point()+
  theme_bw()+
  labs(title = "Membership by Country: Europe",
       subtitle = "Plot 2",
       y = NULL)

north_europe_plot
```

## South America


